import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import QueryClientWrapper from "@/context/queryClientProvider";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const arial = localFont({
  src: "../public/fonts/Arial.ttf",
  variable: "--font-arial",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${arial.variable}`}>
      <body className={`$ ${inter.className} antialiased`}>
        <QueryClientWrapper>
          <AuthProvider>{children}</AuthProvider>
          <Toaster/>
        </QueryClientWrapper>
      </body>
    </html>
  );
}
